const events={
ui:{name:"UI Showdown",desc:"A practical interface-design competition. Teams receive a design brief, create their solution on a computer, and present the final interface to judges.",team:"2 members",time:"10:00–12:30",mode:"Offline • Organizer PCs / approved laptops",fee:"₹100 per team",payment:"UPI / QR payment. Keep the transaction ID for registration." ,rounds:["Brief & setup — 15 min","Design challenge — 90 min","Submission — 15 min","Judging & presentation — 30 min"],rules:["Use only the software allowed by organizers.","AI/tool policy will be announced before the event.","Submit before the deadline.","Judges' decision is final."]},
code:{name:"Code Sprint",desc:"A head-to-head coding tournament. Teams are paired by level and progress through winner/loser brackets.",team:"2 members",time:"10:00–12:15",mode:"Offline • Computer lab",fee:"₹100 per team",payment:"UPI / QR payment. Transaction ID required.",rounds:["Qualifier — 30 min","Head-to-head Round 2 — 30 min","Winner/loser Round 3 — 30 min","Final/finalist evaluation — 30 min"],rules:["Only approved languages are allowed.","No internet unless specifically enabled.","Sharing code between teams is prohibited.","Judges' decision is final."]},
bug:{name:"Bug Hunt",desc:"Incident Response Challenge. Teams act as emergency software engineers: discover bugs, handle incidents, stabilize a system and complete the final boss.",team:"2 members",time:"10:00–13:00",mode:"Offline • Computer lab",fee:"₹100 per team",payment:"UPI / QR payment. Transaction ID required.",rounds:["Bug discovery — 30 min","Incident response — 40 min","System under attack — 40 min","Mystery feature — 30 min","Final submission — 10 min"],rules:["Use only the provided project/environment.","Do not access another team's files.","No unauthorized internet resources.","All submissions must be made before the final deadline."]},
quiz:{name:"Tech Quiz",desc:"A technology-focused team quiz built around knowledge, reasoning and application rather than department-specific questions.",team:"2–3 members",time:"10:00–11:15",mode:"Offline • Classroom",fee:"₹50 per team",payment:"UPI / QR payment. Transaction ID required.",rounds:["Qualification — 20 min","Reasoning round — 20 min","Final rapid round — 20 min","Score verification — 15 min"],rules:["One answer sheet per team.","No phones during active rounds.","Answers must be submitted within the announced time.","Judges' decision is final."]},
checkmate:{name:"Checkmate",desc:"A strategy competition where participants compete through structured chess/strategy rounds.",team:"2 members",time:"10:00–12:00",mode:"Offline • Classroom",fee:"₹50 per team",payment:"UPI / QR payment. Transaction ID required.",rounds:["Round 1 — 20 min","Round 2 — 25 min","Round 3 — 30 min","Final — 30 min"],rules:["Bring a valid ID.","Follow the official match clock and pairing.","No outside assistance during a match.","Arbiter/judges' decision is final."]}};
const key=new URLSearchParams(location.search).get("event")||"ui"; const e=events[key]||events.ui;
document.title=e.name+" | ByteFest 2026";
document.querySelector("#eventName").textContent=e.name; document.querySelector("#desc").textContent=e.desc;
document.querySelector("#facts").innerHTML=`<div><b>Team</b><span>${e.team}</span></div><div><b>Time</b><span>${e.time}</span></div><div><b>Mode</b><span>${e.mode}</span></div><div><b>Registration Fee</b><span>${e.fee}</span></div>`;
document.querySelector("#rounds").innerHTML=e.rounds.map((x,i)=>`<li><b>${i+1}</b>${x}</li>`).join("");
document.querySelector("#rulesList").innerHTML=e.rules.map(x=>`<li>${x}</li>`).join("");
document.querySelector("#payment").innerHTML=`<h3>Payment for ${e.name}</h3><p>${e.payment}</p><div class="payment-box"><strong>${e.fee}</strong><span>Organizer payment details/QR will be shown here after you configure the official UPI ID.</span></div>`;
document.querySelector("#registerEvent").href=`register.html?event=${key}`;
